"""Canonical vehicle types and mapping from COTAÇÃO/CALCULO column names."""

# Canonical list (12 types from BASE_VALORES)
CANONICAL_VEHICLES = [
    "FIORINO - CARGA SECA",
    "VAN - CARGA SECA",
    "LEVE - CARGA SECA",
    "TOCO - CARGA SECA",
    "TRUCK - CARGA SECA",
    "CARRETA 5 EIXOS - CARGA SECA",
    "CARRETA 6 EIXOS - CARGA SECA",
    "VAN - REFRIGERADA",
    "LEVE - REFRIGERADO",
    "TOCO - REFRIGERADO",
    "TRUCK - REFRIGERADO",
    "CARRETA 5 EIXOS - REFRIGERADA",
    "CARRETA 6 EIXOS - REFRIGERADA",
]

# Map COTAÇÃO / FRETE_PESO column names to canonical
TO_CANONICAL = {
    "FIORINO": "FIORINO - CARGA SECA",
    "VAN": "VAN - CARGA SECA",
    "LEVE (3/4)": "LEVE - CARGA SECA",
    "TOCO": "TOCO - CARGA SECA",
    "TRUCK": "TRUCK - CARGA SECA",
    "CARRETA 5 EIXOS": "CARRETA 5 EIXOS - CARGA SECA",
    "CARRETA 6 EIXOS": "CARRETA 6 EIXOS - CARGA SECA",
    "FIORINO - TOTAL": "FIORINO - CARGA SECA",
    "VAN - TOTAL": "VAN - CARGA SECA",
    "LEVE (3/4) - TOTAL": "LEVE - CARGA SECA",
    "TOCO - TOTAL": "TOCO - CARGA SECA",
    "TRUCK - ENTREGA": "TRUCK - CARGA SECA",
    "TRUCK - RETORNO": "TRUCK - CARGA SECA",
    "TRUCK - TOTAL": "TRUCK - CARGA SECA",
    "CARRETA 5 EIXOS - ENTREGA": "CARRETA 5 EIXOS - CARGA SECA",
    "CARRETA 5 EIXOS - RETORNO": "CARRETA 5 EIXOS - CARGA SECA",
    "CARRETA 5 EIXOS - TOTAL": "CARRETA 5 EIXOS - CARGA SECA",
    "CARRETA 6 EIXOS - ENTREGA": "CARRETA 6 EIXOS - CARGA SECA",
    "CARRETA 6 EIXOS - RETORNO": "CARRETA 6 EIXOS - CARGA SECA",
    "CARRETA 6 EIXOS - TOTAL": "CARRETA 6 EIXOS - CARGA SECA",
    "TOCO - TOTAL - REF": "TOCO - REFRIGERADO",
    "TRUCK - ENTREGA - REF": "TRUCK - REFRIGERADO",
    "TRUCK - RETORNO - REF": "TRUCK - REFRIGERADO",
    "TRUCK - TOTAL - REF": "TRUCK - REFRIGERADO",
    "CARRETA 5 EIXOS - ENTREGA - REF": "CARRETA 5 EIXOS - REFRIGERADA",
    "CARRETA 5 EIXOS - RETORNO - REF": "CARRETA 5 EIXOS - REFRIGERADA",
    "CARRETA 5 EIXOS - TOTAL - REF": "CARRETA 5 EIXOS - REFRIGERADA",
    "CARRETA 6 EIXOS - ENTREGA - REF": "CARRETA 6 EIXOS - REFRIGERADA",
    "CARRETA 6 EIXOS - RETORNO - REF": "CARRETA 6 EIXOS - REFRIGERADA",
    "CARRETA 6 EIXOS - TOTAL - REF": "CARRETA 6 EIXOS - REFRIGERADA",
}


def normalize_vehicle(name: str) -> str | None:
    """Return canonical vehicle type or None if not mappable."""
    if not name or not isinstance(name, str):
        return None
    s = name.strip()
    return TO_CANONICAL.get(s) or (s if s in CANONICAL_VEHICLES else None)
